apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: intelligence-service-pdb
  namespace: vartmap
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: intelligence-service
