apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-pipeline
  namespace: vartmap
  labels:
    app: analytics-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-pipeline
  template:
    metadata:
      labels:
        app: analytics-pipeline
    spec:
      containers:
        - name: analytics-pipeline
          image: vartmap/analytics-pipeline:latest
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: vartmap-secrets
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
