apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: vartmap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
        - name: temporal
          image: temporalio/auto-setup:1.25
          ports:
            - containerPort: 7233
          env:
            - name: DB
              value: postgresql
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: vartmap-secrets
                  key: TEMPORAL_DB_USER
            - name: POSTGRES_PWD
              valueFrom:
                secretKeyRef:
                  name: vartmap-secrets
                  key: TEMPORAL_DB_PASSWORD
            - name: POSTGRES_SEEDS
              value: "postgres-temporal"
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: vartmap
spec:
  selector:
    app: temporal
  ports:
    - port: 7233
      targetPort: 7233
